"use strict";
/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Command: npx gltfjsx@6.5.0 react.glb -T
    Author: xenadus (https://sketchfab.com/xenadus)
    License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
    Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
*/
Object.defineProperty(exports, "__esModule", { value: true });
var drei_1 = require("@react-three/drei");
var ReactLogo = function (props) {
    var _a = (0, drei_1.useGLTF)('/models/react.glb'), nodes = _a.nodes, materials = _a.materials;
    return (<drei_1.Float floatIntensity={1}>
      <group position={[8, 8, 0]} scale={0.3} {...props} dispose={null}>
        <mesh geometry={nodes['React-Logo_Material002_0'].geometry} material={materials['Material.002']} position={[0, 0.079, 0.181]} rotation={[0, 0, -Math.PI / 2]} scale={[0.392, 0.392, 0.527]}/>
      </group>
    </drei_1.Float>);
};
drei_1.useGLTF.preload('/models/react.glb');
exports.default = ReactLogo;
